### ISSUE TITLE
Create Auxiliary Power Unit Kit Product Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#104]
Requirements doc: https://docs.google.com/spreadsheets/d/1NRyi_4EzhJYgq4q4HQGat6xuN3QIiiwLNEM1RWpmxzM/edit#gid=0

PIC Content Folder: https://drive.google.com/drive/folders/1PjM9_k4h8rRyd1nkqJy6yFTZeFS7d-8T

See Document containing all descriptions and categories: https://drive.google.com/open?id=10bRBNhFg1YBL4Qqzn45MZZATgf0yzjaN

- [ ] Determine Primary Image (Client has not supplied)
- [ ] Load Product Images (Client has not supplied)
- [ ] Load Verbiage and Product Details to Page using Description and Category doc above.

**Comment by jtuckertw** [comment]
@cmoosman1 This product will need to be shown on the AEF side instead of the subsalve side

@zuzannaczerny - looks great - we'll need to switch out the photos when they arrive from the client.

Oops - they arrived!  Please load these photos, replacing the hood photos currently there.
https://drive.google.com/drive/folders/1l9nZoMSaum2vq6I9mUegHG5b0Xd5F8T_

**Comment by jtuckertw** [comment]
- [ ] Client Requested today that the LADWP Case Study be associated with this product, (LDU) please.

- [ ] @zuzannaczerny The photos showing are not the ones from this folder.  Let me know if this is a dev issue instead of a content issue.

https://drive.google.com/drive/folders/1l9nZoMSaum2vq6I9mUegHG5b0Xd5F8T_

![image](https://user-images.githubusercontent.com/45019034/80434729-6f871700-88af-11ea-8829-d20be746a7c3.png)

**Comment by zuzannaczerny** [comment]
@jtuckertw Yeah here's what it looks from my end: 

<img width="1211" alt="Screen Shot 2020-04-28 at 10 54 50 AM" src="https://user-images.githubusercontent.com/40444952/80520785-c7b92a00-893e-11ea-80ad-d82d1137d767.png">

**Comment by cmoosman1** [comment]
@zuzannaczerny - This is the page you should be editing in WP https://aefenvdev.wpengine.com/wp-admin/post.php?post=3182&action=edit

**Comment by zuzannaczerny** [comment]
@jtuckertw I'm getting a 404 error when I try to open the google links!

**Comment by jtuckertw** [comment]
@zuzannaczerny I totally apologize this request got placed in the wrong ticket.  I got LDU confused with APU/  Your screenshot shows the correct images - thank you!
