### ISSUE TITLE
Create Emergency Partitions (QuikWalls) Product Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#105]
Requirements doc: https://docs.google.com/spreadsheets/d/1NRyi_4EzhJYgq4q4HQGat6xuN3QIiiwLNEM1RWpmxzM/edit#gid=0

PIC Content Folder: https://drive.google.com/drive/folders/1PjM9_k4h8rRyd1nkqJy6yFTZeFS7d-8T

See Document containing all descriptions and categories: Curtain Product details in https://drive.google.com/drive/folders/1r4aiO1gcwWCSn_3x4s11c4vd4nwFJm3G

Choose and Load Primary Image from PIC Content Folder (your choice of which is best).
 Load two best additional Product Images from PIC Content Folder
 Load Verbiage and Product Details to Page using Description and Category doc above.
Note: Client has not chosen a name for this product yet.  Temporarily name it "Emergency Partitions"

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
@cmoosman1 This product will need to be shown on the AEF side instead of the Subsalve side.


@zuzannaczerny This page also looks good.

Although the requirements did not state this can you use the following description: in the blue-gray box instead: "Sturdy, lightweight, portable, antifungal and antibacterial walls suitable for creating safe and private partitioning within hospitals."


![image](https://user-images.githubusercontent.com/45019034/80323371-d0471e80-87df-11ea-99ff-91c68d6e6d93.png)

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
@zuzannaczerny 
Thank you!  Client requested us to do cropping on the Product Page and Application Page product photo such that the top and the bottom of the image are not cut off in the primary picture.  Currently the top is cropped, not giving the viewer a clear indication of the product.
Please Re-crop this image so top and bottom can be seen.
![image](https://user-images.githubusercontent.com/45019034/80435016-4024da00-88b0-11ea-865b-3bdd445e5d27.png)

**Comment by jtuckertw** [comment]
@zuzannaczerny New photos have been added to the Curtains file if we need additional photos for QuikWalls.  Please note that "Emergency Partiitions" should be switched to QwikWalls.

**Comment by zuzannaczerny** [comment]
@jtuckertw does this need to be created on the AEF side?

**Comment by jtuckertw** [comment]
@zuzannaczerny It's already created on AEF as Emergency Partitions - Everything that says Emergency Partitions needs to be switched to "QwikWalls"

**Comment by zuzannaczerny** [comment]
@jtuckertw updated
