### ISSUE TITLE
Create and Load Oasis LDU (Liquid Distribution Unit)

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#106]
Requirements doc: https://docs.google.com/spreadsheets/d/1NRyi_4EzhJYgq4q4HQGat6xuN3QIiiwLNEM1RWpmxzM/edit#gid=0

PIC Content Folder: https://drive.google.com/drive/folders/1PjM9_k4h8rRyd1nkqJy6yFTZeFS7d-8T

See Document containing all descriptions and categories:  https://drive.google.com/open?id=1fWPXBwr2db9grHVypogMBm3L3k1nVChQ

Choose and Load Primary Image from PIC Content Folder (your choice of which is best).
Load two best additional Product Images from PIC Content Folder
Load Verbiage and Product Details to Page using Description and Category doc above.

**Comment by zuzannaczerny** [comment]
@jtuckertw updated!

**Comment by jtuckertw** [comment]
@cmoosman1 - This page is showing on Subsalve but should be on the AEF site.


Zuzanna- this looks good!  One change - the photos that should be used are shown below.
- [x] @zuzannaczerny Please use the photos in the LDU folder: https://drive.google.com/drive/folders/1T7aD2nweVMW8gXmX9NYXqlSkUDUNPLF2

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by cmoosman1** [comment]
@jtuckertw - Has been removed from Subsalve

**Comment by zuzannaczerny** [comment]
@jtuckertw updated this on AEF

**Comment by jtuckertw** [comment]
@zuzannaczerny Product Name is Oasis LDU.  Remove the word Load from all Product Pages, Menus and Product Cards

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
One instance in the gray blue box still remains
![image](https://user-images.githubusercontent.com/45019034/80563634-6fb30f80-89a0-11ea-8aa8-b2e5b973a3d2.png)

**Comment by jtuckertw** [comment]
Resolved
![image](https://user-images.githubusercontent.com/45019034/80564757-8e66d580-89a3-11ea-839b-b3d3dd0d18ac.png)
