### ISSUE TITLE
Create Oxygen Helmet News Card for AEF

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#110]
Per client: Same exact card that is on the subsalve side, linking to same video, but this time with the title as follows:
"Sister Company Subsalve is also in the FIght against COVID-19."

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved on the home/news pages

**Comment by jtuckertw** [comment]
@cmoosman1
 I missed that this article was posted.  I thought the news section was ordered by descending date.  Subsalve seems to be correct but AEF is backwards.

Also - my fault: There was a capital I in Fight by mistake.

**Comment by cmoosman1** [comment]
@jtuckertw - This is fixed just needed to be reordered in WP.

**Comment by jtuckertw** [comment]
Fixed! Thank you! @cmoosman1
