### ISSUE TITLE
Please add the Oxygen Treatment Hood Card to the AEF COVID-19 Application Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#111]
- [ ] Please create an Oxygen Treatment Hood Card for the AEF COVID-19 Application Page

- [ ] Please link this card to the Subsalve site OTH Product page.

**Comment by cmoosman1** [comment]
@jtuckertw - Thats a little outside the system and will require some coding to make this work.

**Comment by jtuckertw** [comment]
@cmoosman1 OK, understood.  Can this be done today?  Or will this take longer than today?

**Comment by cmoosman1** [comment]
@jtuckertw - This is completed and deployed to dev

**Comment by jtuckertw** [comment]
@cmoosman1 Not seeing it yet but this might be pre-push.

**Comment by cmoosman1** [comment]
@jtuckertw - Make sure you do a hard refresh

**Comment by jtuckertw** [comment]
@cmoosman1 I've done it three times.  It is not working.

http://aefenvdev.wpengine.com/covid-19
![image](https://user-images.githubusercontent.com/45019034/80563435-03d0a700-89a0-11ea-9e4a-3e4689a2548d.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in dev

**Comment by jtuckertw** [comment]
Nice - @cmoosman1
