### ISSUE TITLE
Change All references of Emergency Partitions to "QuikWalls"

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#112]
QuikWalls is the product name that will replace "Emergency Partitions" 

- [x] Product Cards

- [x] Product Page

- [x] Application Page

- [x] Mega Menu Product List (New Alpha Positioning)

**Comment by zuzannaczerny** [comment]
@jtuckertw I believe @cmoosman1 has to do the last two? Do I have access to the menu?

**Comment by jtuckertw** [comment]
@cmoosman1 "Quick Walls" should be "QuikWalls" on the application page

**Comment by cmoosman1** [comment]
@jtuckertw - This should be resolved

**Comment by jtuckertw** [comment]
@cmoosman1 Thank you Criss
