### ISSUE TITLE
Revision to Auxiliary Power Tech Data and Specifications

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#113]
**Technical Data & Specifications:**

Revise current text:
Tank Storage capacity (x2) – 1000g (3,785 l)

To this text:
Tank Storage capacity (per tank) - 1000g (3,785 l)

**Comment by zuzannaczerny** [comment]
@jtuckertw Updated

**Comment by jtuckertw** [comment]
Thank you @zuzannaczerny...And they had one more update (facepalm) to the same corrected text...
The line should now read instead- 
Tank Storage capacity (per tank) - 10,000gal (37,850 l)

**Comment by jtuckertw** [comment]
Resolved
![image](https://user-images.githubusercontent.com/45019034/80564140-db49ac80-89a1-11ea-8569-289896683b0f.png)
