### ISSUE TITLE
LADWP Case Study not showing on Oasis LDU Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#115]
@cmoosman1 I added the LADWP Case study to the Oasis LDU but it is not showing after a hard refresh.  Please take a look, and let me know what I need to do in the future.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in dev

**Comment by jtuckertw** [comment]
Perfect - @cmoosman1
