### ISSUE TITLE
Home Page: Accessories,  Bouncing Text, Navigations, button

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#14]
- [x] Accessories - The text bounces during rollover.
- [x] Accessories - Links all lead to the homepage
- [x] Accessories - See All Accessories button does not work

**Comment by victorjaquez** [comment]
@jtuckertw this is fixed on live: http://aefenvprod.wpengine.com/

**Comment by jtuckertw** [comment]
Fixed
