### ISSUE TITLE
Home Page: News Cards 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#16]
- [x] Cards have 5-digit dates: FYI: moosman fixed this on Subsalve.
- [ ] Card links do not work
- [x] When they do work they should lead to new windows

**Comment by victorjaquez** [comment]
@jtuckertw need content for Card links to work

**Comment by jtuckertw** [comment]
Check for links here: https://docs.google.com/spreadsheets/d/1PzHKZ6jR9APVuwbpyVhKs4NxDefh8qjgErKj-IemT1Y/edit#gid=927461111  
First tab, gray content at bottom

**Comment by aguillen1** [comment]
@jtuckertw The News cards link to their respective articles on my end. Ready for QA from you: http://aefenvprod.wpengine.com/
