### ISSUE TITLE
About Us: AEF About Us Content Needed

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#22]
Need Content from Dewan

**Comment by jtuckertw** [comment]
@kylielujan Please work with Dewan for this content.

**Comment by kylielujan** [comment]
Emailed Dewan on 1/28. CC @jtuckertw

**Comment by aguillen1** [comment]
@jtuckertw I'm not seeing the images that are causing the width problem on my end. Were the images removed or am I missing it? http://aefenvprod.wpengine.com/about-us/

Also have they provided the Why AEF specific content for this section yet?

**Comment by aguillen1** [comment]
@jtuckertw Just want to check in again and see if they've provided this information

**Comment by jtuckertw** [comment]
Nothing new. @aguillen1

**Comment by aguillen1** [comment]
@jtuckertw This page currently reads: 

The worldwide leader in engineered inflatables.

Established in 1986, Avon Engineered Fabrications (AEF), Inc. offers customers a full range of products made from elastomeric coated fabrics and state-of-the-art joining and seaming techniques. Formerly known as “Bell Avon,” AEF is a major supplier to the U.S. Army, Air Force, Marines, Navy, and Coast Guard. AEF’s products boast a worldwide reputation for their high-quality and durability. Our class-leading design and production engineering throughout the years have established us as a world-class supplier of industrial coated fabric goods.

Can you remind me what else they wanted here?

**Comment by jtuckertw** [comment]
AEF needs to provide the additional outstanding content - thank you for your work on this @aguillen1

**Comment by aguillen1** [comment]
@jtuckertw About Us content has been updated: http://aefenvprod.wpengine.com/about-us

**Comment by jtuckertw** [comment]
Thank you @aguillen1 !  
About Us Content still needed from Dewan:
![image](https://user-images.githubusercontent.com/45019034/76570680-1e43d500-6473-11ea-948b-ea1fef46d5a9.png)

**Comment by aguillen1** [comment]
@jtuckertw The content in the screenshot has been updates via another task 👍🏼 I believe this one can be closed!
