### ISSUE TITLE
About Us: Timeline: Add AEF Animated Logo 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#25]
AEF Animated Logo https://drive.google.com/file/d/13RCwyv8kA-X7dZdwZ8OIZnzBVDizi8pV/view?usp=sharing

**Comment by victorjaquez** [comment]
@jtuckertw @jthiel16 where exactly does this animated logo go?

**Comment by jthiel16** [comment]
@victorjaquez We were thinking this would go on the About Us page, in the last "2019" spot in the timeline. They would have to provide content that speaks to the brand refresh.

**Comment by victorjaquez** [comment]
@jtuckertw @jthiel16 so are we adding a 2019 - Brand refresh spot to the timeline?

**Comment by jthiel16** [comment]
@victorjaquez @jtuckertw  My two cents: I'm not sure who provided that timeline copy (Wallace or client), but I'd recommend keeping the same number of timeline spots, and swapping the last spot for brand refresh. We're currently listing 3 "production plant openings" and I feel like they might be ok with switching it up a little.

**Comment by victorjaquez** [comment]
@jtuckertw done
