### ISSUE TITLE
AEF/Tallwave Product Detail Content Gaps Summary

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#26]
The following product pages require the following content to be added to the site:

- [x] Bermliners - Have PDF - Tallwave to input
- [x] Decontamination Systems – Remove/Hide Link for now - This item will take time to get.
- [x] Emergency Services – Photos brochures/spec sheets can be found in “Custom” folder - Tallwave to input
- [x] Embankment Tanks – Have photos in AEF catalog folder, but no specs - Tallwave may need to hide link
- [x] Hovercraft Skirts – Only have military spec for this item, but added Notes to ACV folder. AEF will look for other content to add.  Work with AEF for content.  Hide link if insufficient content exists
- [ ] Ground Sheets – AEF Need to develop content
- [x] Fuel Storage - Have PDF - Tallwave to input
- [x] Fire Rescue and Recovery - Remove/Hide Link - AEF Need to develop
- [x] Water Storage - Have PDF - Tallwave to input
- [x] FlexSS - Have Page content - Tallwave to input

**Comment by jtuckertw** [comment]
@aguillen1 added checkboxes to the above list - no other changes.

**Comment by aguillen1** [comment]
- Bermliners: Ready for QA: http://aefenvprod.wpengine.com/berm-liners

- Emergency Services: This has been added to the backend, but I can't see it when I click the page http://aefenvprod.wpengine.com/emergencyservices

- Embankment Tanks: They only provided one photo for embankment tanks, which has been uploaded to the backend http://aefenvprod.wpengine.com/embankment-tanks

- Hovercraft Skirts – I added the information provided in the ACV notes to add more context on the types of hovercrafts/skirts AEF provides, but it's not showing up for me when I open the link here http://aefenvprod.wpengine.com/hovercraft-skirts

- Fuel Storage: Content has been added to the backend http://aefenvprod.wpengine.com/fuel-storage

- Water Storage: Information is in the backend but it's not showing up here http://aefenvprod.wpengine.com/water-storage

- FlexSS: Accordion has been adjusted for consistency, but we don't have the product specifications http://aefenvprod.wpengine.com/flexss

**Comment by jtuckertw** [comment]
@victorjaquez @cmoosman1 
Alejandra added content but it is not showing for these product pages:
- [x] Embankment Tanks
- [x] Hovercraft Skirts
- [x] Fuel Storage
- [x] Water Storage - Page is also missing its title.(in addition to other content)
- [x] FlexSS

- [ ] Need to Hide/Unpublish Fire Rescue and Recovery from Main Nav.

We may need to hide the following after AEF Demo
- [x]  Embankment Tanks
- [x] Ground Sheets

**Comment by jtuckertw** [comment]
@aguillen1 Found Hovercraft Photos - 

- [ ] https://drive.google.com/drive/folders/1SiQnPSKJ3W49OcD2pjunKsZs6ImcDS4z

**Comment by victorjaquez** [comment]
@aguillen1 @jtuckertw fixed the issues that affected rendering of content, everything should work now

**Comment by jtuckertw** [comment]
Thank you @victorjaquez !

**Comment by jtuckertw** [comment]
@victorjaquez I am not seeing the changes - @aguillen1  can you verify?

**Comment by victorjaquez** [comment]
@jtuckertw @aguillen1 fixed

**Comment by jtuckertw** [comment]
@victorjaquez Victor: Thank you! Can you go in and look at it, and make changes as needed, please?  There are some things that are not rendering properly:  Like the hero images being off center.  Also, Alejandra's application updates are also not coming through with this push.

**Comment by victorjaquez** [comment]
@aguillen1 @jtuckertw application page fixed

**Comment by victorjaquez** [comment]
@jtuckertw @aguillen1 also completed checklist above except for Ground sheets

**Comment by jtuckertw** [comment]
@victorjaquez These pages look great - just one item still needs to be accomplished from the list.
 - [ ] Need to Hide/Unpublish Fire Rescue and Recovery from Main Nav.


Thank you for the work on these!

**Comment by victorjaquez** [comment]
@jtuckertw this is done

**Comment by jtuckertw** [comment]
Awesome!  @victorjaquez   TYVM!
