### ISSUE TITLE
Top Nav Needs Registered Mark in logo

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#27]
@victorjaquez  Here is the registered version:

https://drive.google.com/file/d/1fqXNUIaxTC4_szHjneDxlnuXJJPFesIh/view?usp=sharing

**Comment by victorjaquez** [comment]
@jtuckertw this is Subsalve logo not AEF

**Comment by jtuckertw** [comment]
@victorjaquez Ha you are right!  Doing too many things at once.  @jthiel16 would you kindly provide the AEF logo with the mark for use in the header, please?

**Comment by jthiel16** [comment]
@victorjaquez Here's the registered AEF logo: [https://drive.google.com/file/d/1hY56cQJF76J8fmDy8FFnyrxPBxd_O87_/view?usp=sharing](url)

**Comment by victorjaquez** [comment]
@jthiel16 thanks!
