### ISSUE TITLE
Small Business/Hubzone Content Needed From AEF

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#28]
There is no indication on any of the  pages that AEF is a Small business and hubzone status.

**Comment by aguillen1** [comment]
@jtuckertw Can you remind me where this logo is supposed to go? And do I need to pull the image from Google or will they be providing it?

**Comment by jtuckertw** [comment]
@aguillen1  good questions.  Let's position the HUBzone logo in the footer beneath the TUVRheinland logo.  and please pull from Google.  Let's use the Galaxy and Wire image, please: https://www.google.com/search?q=HUBZone+logo&rlz=1C1CHBF_enUS778US781&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj_59LU8tHnAhXxoFsKHRYAA7MQ_AUoAXoECAwQAw&biw=1366&bih=625#imgrc=FU0m-Wc29Wug6M

**Comment by aguillen1** [comment]
@cmoosman1 @victorjaquez Please add this logo to the footer under the TUVRheinland logo
![AEF-HUBZone-Certified-logo](https://user-images.githubusercontent.com/55811485/75081117-563aa680-54cb-11ea-8899-56c411c996ec.png)

**Comment by jtuckertw** [comment]
I'm hoping this one can be completed for tomorrow's walkthrough, please @cmoosman1 @victorjaquez

**Comment by victorjaquez** [comment]
@jtuckertw @aguillen1 does this image link anywhere if they click on it?

**Comment by victorjaquez** [comment]
@jtuckertw @aguillen1 this is done, and temporarily linking to                              https://www.sba.gov/federal-contracting/contracting-assistance-programs/hubzone-program

**Comment by jtuckertw** [comment]
@victorjaquez Awesome!  I don't think they wanted it linked but let's see what they think of it this way - great work!
