### ISSUE TITLE
About Us Page/Products Page - Hero Image and Title Text is incorrect

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#30]
Note: Simply navigating to About Us will NOT recreate this defect.

Steps to Recreate- 
Navigate to Accessories Page
Navigate to Footer
Click About Us
Image will appear: 
![image](https://user-images.githubusercontent.com/45019034/73148732-0eb32d00-407b-11ea-9949-3a7a42762084.png)

Further Issue....once on the About Us Page, Navigating to the Products Page shows this inconsistency with the "News" title:
![image](https://user-images.githubusercontent.com/45019034/73148914-e7a92b00-407b-11ea-94c3-41d3916b6b2f.png)

**Comment by victorjaquez** [comment]
@jtuckertw what the inconsistency with news?

**Comment by jtuckertw** [comment]
@victorjaquez "News" is showing as the title when this is actually the products page - please see the URL in the image.

**Comment by victorjaquez** [comment]
@jtuckertw fixed
