### ISSUE TITLE
Homepage - Featured Case Study Image loading issue

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#31]
Upon Navigating to the Featured Case Study page there is a big white gap that appears for an excessively long time while the lazy load pulls the images in.  Is there a way to correct this?

![image](https://user-images.githubusercontent.com/45019034/73149301-deb95900-407d-11ea-802a-af36ca006b2e.png)

**Comment by victorjaquez** [comment]
@jtuckertw can't replicate on my end, or other devices
