### ISSUE TITLE
Search: Not all pages are indexed correctly

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#32]
Steps to recreate. 
Just typing in single letters will show that the search is not pulling in the content: Trying a, b, c, d, e, I just got the top level pages

example shown: "s"
![image](https://user-images.githubusercontent.com/45019034/73149529-f0e7c700-407e-11ea-8cec-2af849d4327b.png)

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
Something is still wrong with this.  
Typing in "Flex" should lead to FlexSS results...
Typing in "hover" should lead to hovercraft results.
Typing in "acc" should lead to Accessories page

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
Something is still wrong with this.
Typing in "Flex" should lead to FlexSS results
Berm should lead to bermliners

**Comment by jtuckertw** [comment]
Something is still wrong with this.
Typing in "Flex" should lead to FlexSS results
Berm should lead to bermliners

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
Perfect!  Thank you! @victorjaquez
