### ISSUE TITLE
Calendar Items not Working correctly

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#34]
This doc shows the Underwater Intervention event happening  2/4 through 2/6
https://docs.google.com/spreadsheets/d/0B6ZQMsMmAFJLQjRxRHRLSkU1YS1FZXJvVGJYWFpUdG5NOUNz/edit#gid=1508815482

Fixes needed:

- [ ] Must show first date of event (2/4) instead of last date:
![image](https://user-images.githubusercontent.com/45019034/73149911-c4cd4580-4080-11ea-9c66-66369847be47.png)

- [ ] Add to Calendar Must show correct range of dates 2/4-2/6
![image](https://user-images.githubusercontent.com/45019034/73149874-9f403c00-4080-11ea-9796-518261505d51.png)

**Comment by victorjaquez** [comment]
@jtuckertw fixed
