### ISSUE TITLE
Contact Us Form Issues

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#35]
- [ ] Country Code required for phone number - this is not intuitive.  Should be free form 

We should probably be asking for country of user instead of requesting them to type in country code

![image](https://user-images.githubusercontent.com/45019034/73149979-360cf880-4081-11ea-8aa7-4dd9c0f7ad11.png)

- [ ] Email Input issue:

![image](https://user-images.githubusercontent.com/45019034/73150069-9ef47080-4081-11ea-9fdd-6cb898bdec51.png)

**Comment by victorjaquez** [comment]
@jtuckertw i fixed the email error, but the country code changes are out of scope, i'd speak to Criss about this before making these requests

**Comment by jtuckertw** [comment]
Tucker to Refer to client for preferred phone field behavior.

**Comment by jtuckertw** [comment]
Client would like the number 1 auto filled for ease with entering US numbers

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
Fixed
