### ISSUE TITLE
Anytime a link navigates to Subsalve, new window should open rather than within existing window

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#37]
Example:  Linking to any Subsalve Product on this page should instead open a new window rather than take the user away from the AEF site.

http://aefenvprod.wpengine.com/products

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
If it's possible, please do a search for anytime Subsalve is mentioned in a URL  
ex. Homepage: Bouyancy Solutions

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
Homepage Link does not open in alternate window
![image](https://user-images.githubusercontent.com/45019034/74908774-fed5f280-5373-11ea-843f-57377f5421fd.png)

**Comment by jtuckertw** [comment]
Resolved
