### ISSUE TITLE
WesTech Case Study Label Not Showing

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#39]
http://aefenvprod.wpengine.com/westech

![image](https://user-images.githubusercontent.com/45019034/73150491-d9f7a380-4083-11ea-9adb-23fa5bd79ed3.png)

**Comment by victorjaquez** [comment]
@jtuckertw fixed

**Comment by jtuckertw** [comment]
Hmmm this one has returned - I think it has to do with the laptop I am using and how the responsiveness was programmed.  The laptop  (13 in screen ) is showing in Mobile mode and unfortunately the title is covered at that resolution (1366*768)

![image](https://user-images.githubusercontent.com/45019034/75927332-6175c680-5e29-11ea-984c-d2ea9ae8490a.png)

**Comment by victorjaquez** [comment]
@jtuckertw i've tried to replicate this various times by messing with resolution and device and it doesn't happen..

**Comment by jtuckertw** [comment]
@victorjaquez Hmmm It still shows  the error on my side.  It's an in-between state of mobile and desktop.  I see the error on my laptop with no resizing involved.  On desktop (larger monitors) I need to resize the screen to a smaller size to get the error to appear.  I will show it to you on my laptop on Monday if you have a moment.

**Comment by jtuckertw** [comment]
![image](https://user-images.githubusercontent.com/45019034/76187147-d3377280-6191-11ea-8fc0-4c5be0df7fea.png)

**Comment by victorjaquez** [comment]
@jtuckertw pushed some fixes

**Comment by jtuckertw** [comment]
Still not working @victorjaquez .  Yes, I cleared my cache... Maybe work with @cmoosman1, he has this working great for Subsalve.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
Excellent - Thank you @cmoosman1
