### ISSUE TITLE
Header Menu: Products - Removal/Updating of Links without content

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#4]
Aircraft And Heavy Equipment Recovery – Link should direct to Subsalve liftbag page
Bumpers - Remove/Hide Link
Decontamination Systems – Remove/Hide Link for now - This item will take time to get.
Flexitanks - Remove/Hide Link
Ground Sheets – Remove/Hide Link (AEF Need to develop content)
Inflatable Seals - Link should direct to Subsalve seal page
Fire Rescue and Recovery - Remove/Hide Link - AEF Need to develop

**Comment by jtuckertw** [comment]
@victorjaquez Clarification added in initial description.

**Comment by victorjaquez** [comment]
@jtuckertw done

**Comment by jtuckertw** [comment]
@victorjaquez One was missed, not a big deal, but please remove when you can. - 

- [x] Fire Rescue and Recovery - Remove/Hide Link - AEF Need to develop

**Comment by victorjaquez** [comment]
@jtuckertw this is done
