### ISSUE TITLE
Should News link be missing from the Footer?  

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#41]
It's not there for Subsalve or AEF in the designs.  Did not know if this was intentional

**Comment by jthiel16** [comment]
@jtuckertw @victorjaquez Good catch! That was missing from the design, but was NOT intentional.

I think we should go ahead and add that link to the footer, underneath "Case Studies" and before "About Us"

**Comment by jtuckertw** [comment]
Thanks, @jthiel16 
It's only taken 4 months of QA for me to find it....  ugh.  I'm getting way too familiar with these pages!

**Comment by victorjaquez** [comment]
@jtuckertw this is done.
