### ISSUE TITLE
About Us - History Timeline is broken in latest build

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#42]
None of the links are clickable.  Unable to verify the following fixes

The timeline text should be clickable to change the timeline view - fixed in prod
AEF Animated Logo Needed  - fixed in prod
https://drive.google.com/file/d/13RCwyv8kA-X7dZdwZ8OIZnzBVDizi8pV/view?usp=sharing

**Comment by victorjaquez** [comment]
@jtuckertw this is fixed.
