### ISSUE TITLE
Case Studies: LADWP Images not supplied/Loaded

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#43]
Images needed from client, Current images not of LADWP

**Comment by aguillen1** [comment]
@jtuckertw I added the one Oasis photo that was provided for the LADWP case study. I just want to confirm that we haven't gotten any other images from the client for this case study

**Comment by aguillen1** [comment]
@jtuckertw Added all the LADWP pictures I could find to this page. Ready for QA: http://aefenvprod.wpengine.com/los-angeles-department-of-water-and-power

**Comment by jtuckertw** [comment]
perfect
