### ISSUE TITLE
About Us:  Picture sizings are inconsistent for the timeline.  

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#44]
Team these doesn't look right. Maybe make either side flush with the white background?  @jthiel16 to recommend design solution. 1987, 2001, and 2018 need to be addressed

![image](https://user-images.githubusercontent.com/45019034/73624513-521f1580-45fe-11ea-9eae-1eb7d94e647a.png)

![image](https://user-images.githubusercontent.com/45019034/73624461-1e43f000-45fe-11ea-8548-b3db1c8d8c1c.pn

**Comment by jthiel16** [comment]
@jtuckertw @victorjaquez Agreed ... I'd recommend either making the image full-width so it's flush with the white background, or adding a second image so it aligns

**Comment by victorjaquez** [comment]
@jthiel16 @jtuckertw this is the only way to get the best resolution for single pics, the container height and width is too small for a single image. 
<img width="1156" alt="Screen Shot 2020-02-04 at 3 49 15 PM" src="https://user-images.githubusercontent.com/20385537/73794603-0dae8980-4766-11ea-9370-214d25fc21bf.png">

**Comment by victorjaquez** [comment]
@jtuckertw i never got an answer on the comment above.. the container height and width is too small for a single image. Either we stick to two images, or we make the container height bigger and change the tiemline on the left

**Comment by jthiel16** [comment]
@victorjaquez I'd suggest adding a second image if that's not working. How about this one: 

[https://drive.google.com/file/d/1I5qY1L-L_8stkXwsPlLlZp_BDy3ghmtF/view?usp=sharing](url)

![aef-1987-img-2@2x](https://user-images.githubusercontent.com/35710312/74881728-163cbd80-532b-11ea-9d03-845a8f7b8f56.jpg)

**Comment by victorjaquez** [comment]
thx @jthiel16 @jtuckertw what about the rest? http://aefenvprod.wpengine.com/about-us

**Comment by jthiel16** [comment]
@victorjaquez Oh sorry, I didn't see it was more than just that one. I can provide you with images for the others also.

**Comment by victorjaquez** [comment]
@jthiel16 thanks!!

**Comment by jthiel16** [comment]
@victorjaquez No prob ... here you go!

2001 Image #1: 
![aef-2001-img-01@2x](https://user-images.githubusercontent.com/35710312/74888894-9a4b7100-533c-11ea-88a9-e022748f0da9.jpg)

2001 Image #2: 
![aef-2001-img-02@2x](https://user-images.githubusercontent.com/35710312/74888903-a0d9e880-533c-11ea-8085-c19792e3502f.jpg)

2018 Image #2: 
![aef-2018-img-02@2x](https://user-images.githubusercontent.com/35710312/74888911-a800f680-533c-11ea-9b9a-da058ca04005.jpg)

**Comment by victorjaquez** [comment]
@jthiel16 thanks!! @jtuckertw ready

**Comment by jthiel16** [comment]
@victorjaquez I'm noticing some gaps between images on the following:
**1985:** Right image has a gap on the bottom
**1987:** Left image has a gap on the bottom
**2001:** There's a gap between the two images
**2018:** Large gap beneath video. I didn't realize that video was using a different aspect ratio than the rest of the imagery. Does it work better if you use this image?
![aef-2018-img-02v2@1x](https://user-images.githubusercontent.com/35710312/74958208-d1b23000-53c5-11ea-954f-0b4d54b8cc58.jpg)

**Comment by jtuckertw** [comment]
Looks awesome!  @jthiel16 @victorjaquez CLOSED
