### ISSUE TITLE
Image widths unequal with text block

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#45]
Team these doesn't look right. Maybe make either side flush with the white background?  @jthiel16 to recommend design solution. 1987, 2001, and 2018 need to be addressed

![image](https://user-images.githubusercontent.com/45019034/73624513-521f1580-45fe-11ea-9eae-1eb7d94e647a.png)

![image](https://user-images.githubusercontent.com/45019034/73624461-1e43f000-45fe-11ea-8548-b3db1c8d8c1c.pn

**Comment by jthiel16** [comment]
@jtuckertw @victorjaquez Agreed ... I'd recommend either making the image full-width so it's flush with the white background, or adding a second image so it aligns
