### ISSUE TITLE
Homepage: Trusted By carousel no longer works

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#46]
CLicking on the arrows makes the page scroll down OR back to the top instead of the expected behavior of rotating logos.  

Behavior is inconsistent.  works sometimes and sometimes it jumps around.  Cannot determine the steps to recreate, - attempt searching first then using the carousel.

**Comment by victorjaquez** [comment]
@jtuckertw i can't replicate this

**Comment by victorjaquez** [comment]
@jtuckertw cannot replicate this.. have tried various browsers and sizes
![pic](https://user-images.githubusercontent.com/20385537/74879783-1dfa6300-5327-11ea-86f5-0a525440b9d3.gif)

**Comment by jtuckertw** [comment]
Fixed
