### ISSUE TITLE
Headerless SEO issues 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#47]
https://docs.google.com/document/d/1RXzz_aoRyNqmZN-pNhN4gDkJaEE46clVTrBPak4AdFM/edit?ts=5e4acc5e

**Comment by victorjaquez** [comment]
@jtuckertw this is for sargon..

**Comment by jtuckertw** [comment]
@victor Yep it is!  It was for reference for what the other projects said about the headerless issues.  Criss mentioned he fixed these so we can close this.  Thanks!
