### ISSUE TITLE
Data Tables for Products

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#49]
@Aguillen1 I just found this file - I was expecting to find a simple list of Military ID numbers associated with their products.  Instead it contained all of the product spec data.  There is way too much data in here to enter in one day - If you can create the Product Spec boxes for each product, please, I will do the data entry for the tables.

https://docs.google.com/spreadsheets/d/1Y-S-pmR9cqZT9UlK3HhnrpibVJVDLh2B/edit#gid=1395874510

**Comment by aguillen1** [comment]
@jtuckertw Just so we have this here for reference:

- Berm Liners - Done Ready for QA http://aefenvprod.wpengine.com/berm-liners

- Fuel Tanks - already has a table. The one provided in the spreadsheet above has about 70 products listed out. Do we want to replace with these? Waiting for client response on this

- Water Tanks (Storage) - Done ready for QA http://aefenvprod.wpengine.com/water-storage



- Tank Accessories- not a product/page

- Washers - not a product/page

- Systems - not a product/page

- BPU Accessories - not a product/page

**Comment by jtuckertw** [comment]
You totally rock @aguillen1  - THANK YOU FOR ALL YOUR WORK THIS WEEK!  Hope I made that clear.  Have a great weekend!
