### ISSUE TITLE
Product Main Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#50]
- [x] Aircraft Lift Bag should be plural and have photo from Subsalve site
- [x] Embankment Tanks to have photo (will this appear after Victor refreshes backend content?)
- [x] Hovercraft Skirts to have photos (will this appear after Victor refreshes backend content?)
Photo location- https://drive.google.com/drive/folders/1SiQnPSKJ3W49OcD2pjunKsZs6ImcDS4z
- [x] Inflatable Seals - will have Pipe Pluggers Photo from Subsalve and link to Subsalve.

These may need to be hidden after Demo
- [x] Ground Sheets may need to hide if insufficient info
- [x] Hovercraft skirts - may need to hide if insufficient info

**Comment by aguillen1** [comment]
Changed Aircraft Lift Bags to "Aircraft and Heavy Equipment Recovery" per our conversation this morning. There's currently no image for ground sheets, otherwise this page should also be good to go: http://aefenvprod.wpengine.com/products

**Comment by victorjaquez** [comment]
@jtuckertw @aguillen1 i hid/drafted the ground sheets and hovercraft skirts. Once we have content for them we can just undraft them on the backend and they will show up on the site.

**Comment by aguillen1** [comment]
@jtuckertw This task should be complete

**Comment by jtuckertw** [comment]
@victorjaquez Please unhide hovercraft skirts.  It's looking like they will get us the content needed for this product.  Thank you!  http://aefenvprod.wpengine.com/products

**Comment by victorjaquez** [comment]
@jtuckertw this is done

**Comment by jtuckertw** [comment]
Thank you @victorjaquez !
