### ISSUE TITLE
Embankment Tank Photo

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#52]
Please load the following photo to the Embankment Tank page 
https://drive.google.com/file/d/1_xi-CLfwOh8yNKHB9jIDLdZ6J3IgSowo/view?usp=sharing

**Comment by victorjaquez** [comment]
@jtuckertw done

**Comment by jtuckertw** [comment]
Nice work @victorjaquez Looks awesome!
