### ISSUE TITLE
Product Specifications Data Table Updates

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#54]
Revised - Marketing focused tables

https://drive.google.com/open?id=1WFEdoxB5O5yPIQNllW2s7a3IzzHc5LWf

AEF has requested that we enter Metric units.  I pushed back and asked for them to convert.

**Comment by aguillen1** [comment]
@jtuckertw Added tables to everything except ground sheets per our conversation. I wasn't sure what unit of measurement was being used in the berm liner dimensions, so I left them blank: http://aefenvprod.wpengine.com/berm-liners/

**Comment by jtuckertw** [comment]
Tucker to verify

**Comment by jtuckertw** [comment]
@aguillen1 or @zuzannaczerny Please add a row to indicate "Standard" at the top of these tables.

Please ensure that both standard and Metric fall on a dark shaded line please.

**Comment by aguillen1** [comment]
@jtuckertw Do you need me to help on these or is Zuzanna amazing and completed all of them?

**Comment by jtuckertw** [comment]
Would you be able to do them, please?  @aguillen1 ?

**Comment by aguillen1** [comment]
@jtuckertw Added "Standard" and made the labels show up on a dark shaded line in the back end

**Comment by jtuckertw** [comment]
Perfect - thank you @aguillen1
