### ISSUE TITLE
Remove and Replace Current Articles about acquisition

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#55]
Replace with this article instead: https://drive.google.com/open?id=1bQRxGHnI5Uzxl2QUave7kuWhGN2hPg48

**Comment by victorjaquez** [comment]
@jtuckertw done

**Comment by jtuckertw** [comment]
@victorjaquez New article looks great.  The original two still need to be removed: "Avon Rubber sells..." and "Avon Divests..."

**Comment by victorjaquez** [comment]
@jtuckertw sorry this is done, i didn't understand initial instructions to actually delete not just replace

**Comment by jtuckertw** [comment]
Perfect - thank you!
