### ISSUE TITLE
Product Detail - Product Image Carousel off-center

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#58]
Something in the last build knocked the images on the product page off-center.  I think this is a template issue as it is happening on ALL product pages.

Please realign - example page 
http://aefenvprod.wpengine.com/embankment-tanks/

**Comment by jtuckertw** [comment]
Thank you! @victorjaquez All images look great now

**Comment by jtuckertw** [comment]
Issue exists on AEF and Subsalve (Subsalve example shown)
reopened.  Replication steps: Navigate to any product detail page, and shrink width slowly.

Sample Page: http://aefenvprod.wpengine.com/fuel-storage

There are three views depending upon the width.  Large Desktop, Smaller desktop, and Mobile.
The smaller desktop view shows the centering issue.

![image](https://user-images.githubusercontent.com/45019034/76561258-28100d00-6460-11ea-9686-4b7cf14c6545.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
Perfect - tyvm @cmoosman1 !
