### ISSUE TITLE
About Us: 2018 on Timeline - AEF Animated logo slower

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#60]
- [x]  @jthiel16 AEF would like the AEF image associated with 2018 to slow down, estimated 25-50%.  WOuld you be able to provide a new file to @victorjaquez to upload please?

- [x] @victorjaquez to upload left side animated gif.  Client would also like the padding for this image to be corrected, please.  There is visible dark space between the image and the larger text box below.

- [x] @jthiel16 Client would like a new image on the right hand side of the page if possible, please.  They were leaning toward a fairly current image of their building if we have one.

- [x] @aguillen1 would you be able to update the right hand side photo when one has been selected, please?

**Comment by jthiel16** [comment]
@jtuckertw @aguillen1 We don't have a great selection of building shots unfortunately, but here's one of their facility showing their old logo (next to the animated new one) that we could use:

![aef-facility-18](https://user-images.githubusercontent.com/35710312/75932321-5bd1ae00-5e34-11ea-841a-48c4e93f075c.jpg)

Zuznanna is working on adjusting the animation also. Will update when that's ready.

**Comment by jtuckertw** [comment]
They were thinking more of an outside shot...but we already have a few of those already on the timeline.  I really like this one you found! Especially with the logo, prominently featured.  Nice!  Let's give this one a shot.

**Comment by victorjaquez** [comment]
@jtuckertw @jthiel16 waiting on new gif from Zuzanna, she had computer issues yesterday and is finding a workaround with the temp laptop that Tony gave her. It's a simple upload on my end so not very critical

**Comment by jtuckertw** [comment]
@victorjaquez @jthiel16 No worries - thank you all for working on this!

**Comment by victorjaquez** [comment]
@jtuckertw this is done

**Comment by jthiel16** [comment]
@victorjaquez I'm still seeing that dark space beneath the video. Are you able to make that a white background color and vertically center the gif within that container?
<img width="531" alt="Screen Shot 2020-03-10 at 9 13 52 AM" src="https://user-images.githubusercontent.com/35710312/76334044-c0b35b00-62af-11ea-88ae-f91feb11ffb9.png">

**Comment by victorjaquez** [comment]
@jthiel16 i haven't pushed it my bad haha, pushing now, check in 5!

**Comment by jthiel16** [comment]
Ah, got it! Ok thanks!

**Comment by victorjaquez** [comment]
@jthiel16 good to go now!

**Comment by jthiel16** [comment]
Looks great, thanks @victorjaquez!

**Comment by jtuckertw** [comment]
Looks perfect!  @victorjaquez @jthiel16
