### ISSUE TITLE
Remove Photo with airplane in it from Berm Liner page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#63]
http://aefenvprod.wpengine.com/berm-liners

![image](https://user-images.githubusercontent.com/45019034/75931797-0943c200-5e33-11ea-94da-23599a71511d.png)

Replace with another Berm Liner image - OR if none other are available, please duplicate an existing valid image so the page does not break.

**Comment by aguillen1** [comment]
@jtuckertw Removed: http://aefenvprod.wpengine.com/berm-liners

**Comment by jtuckertw** [comment]
@aguillen1  Looks great!  Thank you.

It looks like you tried to do the conversions for metric in the product specs - We may need to wait for them to provide us the data,  On one of the calls they mentioned they would be rounding some of the numbers.

**Comment by aguillen1** [comment]
@jtuckertw Have we gotten these tables back from them? I can round the numbers if needed as well

**Comment by jtuckertw** [comment]
@aguillen1 no tables yet.

**Comment by jtuckertw** [comment]
closing
