### ISSUE TITLE
Phone Number Edits

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#66]
- [x]  Homepage and Contact page: +1 should be removed and instead replaced with help text, "Please enter your country code and phone number."
http://subsalve.wpengine.com/
http://subsalve.wpengine.com/contact
 
- [ ]  On Footer and Contact page: Revise Subsalve phone number to read:
 +1 (601) 889-9050

**Comment by victorjaquez** [comment]
@jtuckertw this AEF not subsalve ticket board. But i did the country code portion, not sure about the phone number, will wait on instruction

**Comment by jtuckertw** [comment]
@victorjaquez The new instructions looks great!  Thank you.  

Please let me know what instruction you need to change the footer and the contact page phone number.  It currently says (601) 889-9050 but should say +1 (601) 889-9050

**Comment by cmoosman1** [comment]
@jtuckertw - Both issues are resolved

**Comment by jtuckertw** [comment]
Thank you @cmoosman1 !
