### ISSUE TITLE
Client Identified Issue: Download Catalog button disappears at certain screen widths

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#67]
Appears on PIC and Subsalve:
1) Replication: Open http://subsalve.wpengine.com/
2) Minimize browser allowing resizing of window
3) Resize window from full screen width to hamburger menu.

The following responsive "breakpoints" will reveal missing Download Catalog buttons:

![image](https://user-images.githubusercontent.com/45019034/76559833-22fd8e80-645d-11ea-9c56-902d563a1e2b.png)

![image](https://user-images.githubusercontent.com/45019034/76559867-34469b00-645d-11ea-8096-c5cad8095127.png)

**Comment by cmoosman1** [comment]
@jtuckertw - Same as Subsalve this is by design.

**Comment by jtuckertw** [comment]
The client will not accept this.  The download button should always be present in the menu.

We will need to switch to hamburger mode earlier if needed.

**Comment by cmoosman1** [comment]
@jtuckertw - At 1300px we switch to mobile menu

**Comment by jtuckertw** [comment]
@cmoosman1 The Logo is missing when it reverts to hamburger
Showing Edge
![image](https://user-images.githubusercontent.com/45019034/77114961-ab92a680-69ea-11ea-9cdd-1238dba16f83.png)

**Comment by jtuckertw** [comment]
@cmoosman1 Maybe the logo disappears only on certain pages? Tested in Edge. Products
aefenvprod.wpengine.com/products
I seem to be getting it to disappear on all pages though.
Video Here: https://www.loom.com/share/3c41fcdc269a4d97aaf68bdae7e89ea5

![image](https://user-images.githubusercontent.com/45019034/77268422-15b58080-6c63-11ea-9a57-029496aacf59.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved.

**Comment by jtuckertw** [comment]
thank you @cmoosman1 !
