### ISSUE TITLE
Titles of Pages are getting messed up

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#68]
3/17 update:  this issue seems to only be appearing on MSEdge now.

About Us Page shows "Contact" as page title
Contact shows "News" as page title

![image](https://user-images.githubusercontent.com/45019034/76888309-ec4ebc00-6840-11ea-93a5-295f61f33ec9.png)

**Comment by jtuckertw** [comment]
This recording demonstrates a Microsoft Edge test that shows the page titles being mixed up, the header row links not working, the events formatting in vertical fashion, and the About Us page being messed up re: images loading.

https://drive.google.com/file/d/1PiQ1RjIgXehWE2vRhhs6WeVrC4M5bC_s/view

**Comment by jtuckertw** [comment]
@cmoosman1  Here is a video showing the path for "Downloads" to show as title for the Contact Us page..
Navigate to Applications in Main menu
Click See Accessories
Click Contact Us in the footer

https://www.loom.com/share/d89d17cf4dc8492481d76cc1e234c95b

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
Fixed Thank you @cmoosman1
