### ISSUE TITLE
Berm Liner Product Details Text Update 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#69]
Safety and Ease-of-Use

·         2 Drains to remove captured or standing water

·         Designed footprint of liner covers berm storage area up to 150% capacity of the collapsible storage tank

·         Built using Mil Spec. materials (ATPD 2262 and Mil-B-53081) for long life and outdoor exposure

·         Can be made to custom commercial or military specifications in any size required

**Comment by aguillen1** [comment]
@jtuckertw Update made: http://aefenvprod.wpengine.com/berm-liners

**Comment by jtuckertw** [comment]
@aguillen1 awesome tyvm
