### ISSUE TITLE
Microsoft Edge: Events messed up

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#70]
THis is also occurring on Subsalve

![image](https://user-images.githubusercontent.com/45019034/76563307-61e31280-6464-11ea-9b09-8d20fe90b1f3.png)

**Comment by victorjaquez** [comment]
@jtuckertw i cant replicate this on **AEF** nor **Subsalve**.. tried on edge on work and personal laptop

**Comment by jtuckertw** [comment]
@victorjaquez I have tested and confirmed on two separate computers using Edge.  Let's walk through this today.

**Comment by cmoosman1** [comment]
@jtuckertw - This issue is resolved

**Comment by jtuckertw** [comment]
Thank you @cmoosman1
