### ISSUE TITLE
Embankment Tanks to be hidden

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#71]
Client was unable to get sufficient prod detail for go live.  Please hide product cards, menu options, and product details.

**Comment by aguillen1** [comment]
@jtuckertw Removed embankment tanks as a live page

**Comment by jtuckertw** [comment]
@victorjaquez Embankment tanks still shows in main menu
![image](https://user-images.githubusercontent.com/45019034/76900282-48700b00-6856-11ea-9f8b-d0f4d1d99dae.png)

**Comment by victorjaquez** [comment]
@jtuckertw there was an extra step on this that wasn't done, @aguillen1 we have to remove it from the menu's in https://aefenvstage.wpengine.com/wp-admin/nav-menus.php sorry for not clarifying that

**Comment by aguillen1** [comment]
@jtuckertw Embankment tanks was not on the menu anymore when I checked

**Comment by jtuckertw** [comment]
Resolved!
