### ISSUE TITLE
MSEdge: Homepage: Press Release leads to Google Sign In

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#73]
![image](https://user-images.githubusercontent.com/45019034/76563986-84c1f680-6465-11ea-9d6d-e98fee4e19ee.png)
  Button leads to Google Docs log in.

**Comment by cmoosman1** [comment]
@jtuckertw - I have run through this and everything is working as expected

**Comment by jtuckertw** [comment]
Hmm Tested on two separate computers and get Google docs log in.  

https://drive.google.com/open?id=1J4loxnWdLWUPYdOt4bWBE3O7TIB8XYI-

**Comment by victorjaquez** [comment]
@jtuckertw the google docs login is a google thing. The owner of the link needs to change the permissions settings to be able to be viewed by anyone with the linkk

**Comment by jtuckertw** [comment]
This shows up in chrome without a log in but probably because I am a trusted user of the doc...investigating Firefox.  same.  Revising to a Content bug as this may require changing the permissions on the base link.

![image](https://user-images.githubusercontent.com/45019034/76889458-db06af00-6842-11ea-94e4-91653c87dabf.png)

**Comment by aguillen1** [comment]
@jtuckertw Same comment as the other task that's asking for this – I don't know how to go about this without having an actual website link as I am also not the owner of the document.

**Comment by jtuckertw** [comment]
Resolved!
