### ISSUE TITLE
Minor Defect - Contact Us button reappears after form submission

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#75]

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved and working as expected

**Comment by jtuckertw** [comment]
Thank you @cmoosman1  I think this change may have reverted the Help text fix in the phone field.  Can you look into that when you get a moment, please?

**Comment by cmoosman1** [comment]
@jtuckertw - This issue is resolved

**Comment by jtuckertw** [comment]
Thank you @cmoosman1
