### ISSUE TITLE
AEF Home Page Tab Says "Products" Should say "AEF"

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#77]
Home Page does not update to say "Subsalve" when navigating from a different page 
![image](https://user-images.githubusercontent.com/45019034/76566993-1f710400-646b-11ea-91c6-c2862a8d443c.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
![image](https://user-images.githubusercontent.com/45019034/76899960-b9fb8980-6855-11ea-87fa-c32c8ec8bf2b.png)

**Comment by jtuckertw** [comment]
Fixed!
