### ISSUE TITLE
About Us: Timeline Edits from Client (3/12)

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#78]
@aguillen1 - I have not reviewed this in detail - yell if you need me to dive in and clarify.

Please see below timeline. I believe the main issue is a misunderstanding for 2001. In 2001, Bell Avon became Avon Engineered Fabrications by name. The site states we were purchased by Performance inflatables which is incorrect. The Purchase by Performance inflatables was in 2018, which can also be incorporated into the “Brand rebrand” – 2018 of the Our History timeline.

 

I hope this clarifies the timeline. Thanks

 

 

 

1985 - Formed as a Joint Venture between Bell Aerospace Textron and Avon Rubber plc, under the name Bell Avon Inc. in Picayune MS. Bell Avon Inc. established as the sole source supplier of hovercraft skirting systems to the Navy’s LCAC (Landing  craft air cushioned) program.

 

1987 - Bell Avon, Inc. began supplying collapsible fabric water and fuel storage systems to the US Military.  Since that initial offering, we continue to supply durable high quality storage systems to all branches of the US military. The company has since built and delivered over 30,000/ 15,000 tanks to the US military.

 

2001 - Bell Avon, Inc. Became Avon Engineered Fabrications, Inc., a wholly owned subsidiary of Avon Rubber and Plastics, Inc.

 

2005 – Avon Engineered Fabrications, Inc. Introduces  lightweight fuel resistant rubber coated fabric storage tanks to the US Marine Corps as part of their expeditionary fuels program.

 

2018 - Avon Engineered Fabrications Inc. Is purchased by Performance Inflatables Company, LLC and becomes Avon Engineered Fabrications, LLC

**Comment by aguillen1** [comment]
@jtuckertw This update has been made: http://aefenvprod.wpengine.com/about-us

**Comment by jtuckertw** [comment]
@aguillen1 Perfect - The client was not happy with the phrase "Brand Rebrand"  Any creative suggestions that will fit?

**Comment by aguillen1** [comment]
@jtuckertw Changed it to "Brand Refresh" http://aefenvprod.wpengine.com/about-us

**Comment by jtuckertw** [comment]
Love it!  @aguillen1
