### ISSUE TITLE
Using back button to return to Product Overview from Products Detail results in Blank Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#79]
Navigate to Products
Navigate to Water Storage (or Any Product Page)
Use back button to return to Products.
Empty Product Overview Page:
![image](https://user-images.githubusercontent.com/45019034/76569724-09fed880-6471-11ea-9556-4f916734eb6f.png)

**Comment by victorjaquez** [comment]
@jtuckertw not sure what to do here, can't replicate, and seems like a cache or network issue.. data has to load to see it. But i can't replicate it

**Comment by jtuckertw** [comment]
Video Posted here:

https://drive.google.com/file/d/1El1HY8ZjEeAGe451U2jjervwRUdb9_gl/view

**Comment by jtuckertw** [comment]
closed
