### ISSUE TITLE
Footer: LinkedIn and Facebook Links inoperable

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#8]

**Comment by victorjaquez** [comment]
@jtuckertw need correct social media links

**Comment by kylielujan** [comment]
https://www.linkedin.com/company/aef-llc/

https://www.facebook.com/pages/Avon-Engineered-Fabrications/160270410672431

**Comment by aguillen1** [comment]
@jtuckertw These are linked in the backend and show up in the live production site 👍🏼 http://aefenvprod.wpengine.com/

**Comment by jtuckertw** [comment]
Perfect
