### ISSUE TITLE
MS Edge: News article links to Google Log In page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#80]
Homepage, News, and all other places where News lives.

![image](https://user-images.githubusercontent.com/45019034/76570278-39621500-6472-11ea-9a9b-21ada082acae.png)

**Comment by victorjaquez** [comment]
@jtuckertw we need to make those pdfs public, thats all

**Comment by jtuckertw** [comment]
Agreed - Transferring to content.

**Comment by aguillen1** [comment]
@jtuckertw I don't know how to do this. Do they have this uploaded to a website that we can link to?

**Comment by jtuckertw** [comment]
Solved.
