### ISSUE TITLE
MS Edge: Main Nav Links not working

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#81]
News, About Us, Contact do not work in edge
Same issue exists for Subsalve

![image](https://user-images.githubusercontent.com/45019034/76576356-12f6a680-647f-11ea-80cf-046d7d21678f.png)

**Comment by victorjaquez** [comment]
@jtuckertw this works on my end on edge, also on personal laptop

**Comment by jtuckertw** [comment]
I have cleared cache and tested on two separate machines.  This is not working still.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved and working as expected

**Comment by jtuckertw** [comment]
Perfect - Thank you, @cmoosman1
