### ISSUE TITLE
Client Request - Hovercraft Skirts

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#82]
Hovercraft Skirts are the biggest $ value item for AEF and client would like these to always appear first in Products on Main Nav and on Product Overview screen 

http://aefenvprod.wpengine.com/products

**Comment by cmoosman1** [comment]
@jtuckertw - This is now the first item in the products menu

**Comment by jtuckertw** [comment]
Thank you @cmoosman1 

@aguillen can you reorder the hovercraft skirts on http://aefenvprod.wpengine.com/products to make them appear first?

**Comment by aguillen1** [comment]
@jtuckertw I can't – This page is organized by alphabetical order.

**Comment by jtuckertw** [comment]
OK will notify client.

**Comment by jtuckertw** [comment]
Notified
