### ISSUE TITLE
About Us verbiage - "Blue Section"

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#83]
The Polyurethane Difference

AEF is the only major flexible containment supplier that offers polyurethane-coated fabrics with an anti-wicking encapsulated edge in all of our products. We use high-strength synthetic base fabrics including nylon, polyester and Kevlar coated with urethane and nitrile blends. The result? Our bladders are more puncture-, abrasion-, and chemical-resistant than other flexible storage bladder. This allows for a longer service life that holds up longer against the elements.

Give Us Your Toughest Challenge

AEF, with its Military pedigree, has a legacy of meeting tough customer challenges with innovative solutions, including custom products for specialized applications.

**Comment by aguillen1** [comment]
@jtuckertw This change has been made: http://aefenvprod.wpengine.com/about-us

**Comment by jtuckertw** [comment]
Looks great!  Thank you @aguillen1
