### ISSUE TITLE
Remove Image Switch, from all case studies images.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#84]

**Comment by victorjaquez** [comment]
@jtuckertw done

**Comment by jtuckertw** [comment]
It still shows.

https://drive.google.com/file/d/1xuWXZHoiJep3PiQXP8rgpzW46b9EaMR-/view

![image](https://user-images.githubusercontent.com/45019034/76899614-23c76380-6855-11ea-9844-788cdb9baf14.png)

**Comment by victorjaquez** [comment]
@jtuckertw this is AEF issue tracker.. where it is removed. Subsalve and AEF code repo's are two different code bases

**Comment by jtuckertw** [comment]
sorry switching back and forth between both very frequently today.  Fixed.  Thank you @victorjaquez
