### ISSUE TITLE
Product Table Updates

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#85]
Unlike the subsalve side, AEF would like the metric units inline with the standard measurements as shown on these tables: 
https://drive.google.com/drive/folders/12Ch3uvc3KJMsYph2eKC5lx2CdlCmeIjp

- [x] Water Tanks
- [x] Fuel Tanks
- [x] Ground Sheets
- [x] Berm Liners

**Comment by aguillen1** [comment]
@jtuckertw These tables have been updated! Just as a reminder, ground sheets remains unpublished because we don't have enough information from them. The table is for this page was updated in the backend regardless 👍🏼

**Comment by jtuckertw** [comment]
These are beautiful - thank you @aguillen1
