### ISSUE TITLE
Icons incorrect on AEF Application Cards

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#86]
Images got a bit jumbled.

1) Need the dead frog image, please @jthiel
2) Current image in 3 needs to be here in 2.  The emergency sign
3) Specialty Projects - Needs to have the ruler image. please @jthiel16 
4) Current image in 2 needs to be in 4.

![image](https://user-images.githubusercontent.com/45019034/77702595-2113ef00-6f76-11ea-91c4-4b1edb3f1027.png)

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw 
1. Dead frog (lol): [https://drive.google.com/file/d/1FBAOlGG9gQh0uggrrkkt1m9p1LxBJzc5/view?usp=sharing](url)
2. Emergency: [https://drive.google.com/file/d/1GmNwOxJjFPcB4nEp3_u32zhgyr7licPU/view?usp=sharing](url)
3. Specialty: [https://drive.google.com/file/d/1FLQXjFQ3cABpNaPAlASqajr5nSKCSCgk/view?usp=sharing](url)
4. Buoyancy: [https://drive.google.com/file/d/1H0oTbZJrFHmZVvv_jWVnHB4KHH47zPPd/view?usp=sharing](url)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
These look awesome - thank you @cmoosman1 and @jthiel16
