### ISSUE TITLE
HoverCraft still has Subsalve verbiage

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#87]
Jeff to add the HC verbiage here. @aguillen1

**Comment by jtuckertw** [comment]
Supplied by Dewan

[LCAC product data.docx](https://github.com/Tallwave/AEF-PIC/files/4394943/LCAC.product.data.docx)

**Comment by aguillen1** [comment]
Updated! http://aefenvprod.wpengine.com/hovercraft-skirts

**Comment by jtuckertw** [comment]
THank you @aguillen1 !
