### ISSUE TITLE
AEF Fuel Tanks Needs All AEF Accessories loaded

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#88]
Currently has none associated to it.

http://aefenvprod.wpengine.com/fuel-storage

![image](https://user-images.githubusercontent.com/45019034/77727361-63a9eb80-6fb7-11ea-93a9-ec79dd1a2f80.png)

**Comment by aguillen1** [comment]
@jtuckertw All accessories have been added to this page: http://aefenvprod.wpengine.com/fuel-storage

**Comment by jtuckertw** [comment]
Fantastic! Thank you, @aguillen1 !
