### ISSUE TITLE
AEF LLC

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#92]
Anywhere AEF is referred to as Inc, should be renamed as LLC.

**Comment by aguillen1** [comment]
@jtuckertw I only saw Inc. used in the About Us page – please let me know if you spot it anywhere else I may have missed! http://aefenvprod.wpengine.com/about-us

**Comment by jtuckertw** [comment]
Looks good! THank you @aguillen1 !
