### ISSUE TITLE
About Us - LSEP character in Value Statement

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#94]
Additional weird character in last sentence of Value

Recommended fix - Cut content snip from Wordpress and paste content into notepad then copy and paste from notepad to WordPress.  This should remove the weird character formats per @cmoosman1

**Comment by aguillen1** [comment]
Made that fix using the recommended steps: http://aefenvprod.wpengine.com/about-us

**Comment by cmoosman1** [comment]
@aguillen1 - Can you send me a screen shot Im not seeing any issues on the page?

**Comment by aguillen1** [comment]
@cmoosman1 There shouldn't be an issue anymore! The value section should be good to go 👍🏼
<img width="483" alt="Screen Shot 2020-04-13 at 9 52 04 AM" src="https://user-images.githubusercontent.com/55811485/79140322-a8ca6d80-7d6c-11ea-8790-cb396a658527.png">

**Comment by jtuckertw** [comment]
perfecto - TYVM! @aguillen1 and @cmoosman1
