### ISSUE TITLE
Mobile: iPhone8 Home Page Submit button not showing

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#98]
Note: Cannot replicate on iPhone 7S  which seems to use the same codebase.  

Client sent screen shot:
![image](https://user-images.githubusercontent.com/45019034/78940716-2a6b8400-7a6b-11ea-8cd5-75a1d19bee17.png)

**Comment by cmoosman1** [comment]
@jtuckertw - I dont have an iPhone 7 but tested on iPhone 6 and in the dev tools this is resolved and working.

**Comment by jtuckertw** [comment]
TYVM - @cmoosman1
